### ISSUE TITLE
Segfault in VirtualBox

### ISSUE THREAD

**Issue by ApolloLV** [PADrend/PADrendComplete#4] opened 2018-10-13 13:30 UTC
I was trying to run PADrend in a debian stretch VM, but the program exits with a segmentation fault:
```
-------------------------------------------------------------------------------
PADrend 1.0.0 -- Platform for Algorithm Development and rendering (PADrend.de)
-------------------------------------------------------------------------------
Build:	2018-10-13 14:28.47 | 64 bit | release
Libs:	EScript 0.7.2 Egon (https://github.com/EScript)
	Freetype 2.6.3 (www.freetype.org)
	SDL 2.0.5 (www.libsdl.org)
	SDL_image 2.0.1 (www.libsdl.org/projects/SDL_image/)
	SDL_net 2.0.1 (www.libsdl.org/projects/SDL_net/)
	curl 7.52.1 (curl.haxx.se)
	libarchive 3.2.2 (www.libarchive.org)
	libxml 2.9.4 (xmlsoft.org)
	libzip (www.nih.at/libzip)
	sqlite 3.16.2 (www.sqlite.org)
-------------------------------------------------------------------------------
Loading Util scripts...
Initializing PADrend...
[[--   Loading PADrend modules...   --]]
Initializing LibRenderingExt...
Initializing PADrend/EventLoop...
Initializing PADrend/HID...
Initializing PADrend/Navigation...
Initializing PADrend/NodeInteraction...
Initializing PADrend/Picking...
Initializing PADrend/RemoteControl...
Initializing PADrend/SceneManagement...
Initializing PADrend/Serialization...
Initializing PADrend/SplashScreen...
Initializing PADrend/SystemUI...
[[--   Creating Window...   --]]
Creating Rendering Context              ok.
OpenGL vendor: VMware, Inc.
OpenGL renderer: Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits)
OpenGL version: 3.0 Mesa 13.0.6
OpenGL shading language version: 1.30
Initializing PADrend/UITools...
Initializing PADrend/CommandHandling...
Initializing PADrend/GUI...
Initializing PADrend/GUI/MainToolbar...
Initializing PADrend/GUI/MainWindow...
Initializing PADrend/GUI/ToolsToolbar...
Init network system                     ok.
[[--   Loading Plugins...   --]]
Initializing Effects...
Initializing NodeEditor...
Initializing NodeEditor/GUI...
Initializing NodeEditor/NodeConfig...
Initializing NodeEditor/StateConfig...
Initializing NodeEditor/Tools...
Initializing NodeEditor/Transformations...
Initializing NodeEditor/BehaviourConfig...
Initializing SceneEditor...
Initializing ObjectTraits...
Initializing SceneEditor/GroupStorage...
Initializing SceneEditor/NodeRepeater...
Initializing SceneEditor/ObjectEditor...
Initializing SceneEditor/ObjectPlacer...
Initializing SceneEditor/ObjectPlacer...
Initializing SceneEditor/ObjectPlacer/BuildinLib...
Initializing SceneEditor/Selection...
Initializing SceneEditor/TransformationTools3...
Initializing SceneEditor/VisualHelper...
Initializing Tests...
Initializing Tools...
[[--   Plugins loaded (0.23 sec)   --]]
Call extensions [PADrend_Init]...
Creating SceneGraph elements...
Creating main toolbar                   ok.
[[--   PADrend started in 0.35 sec.   --]]
Starting EventLoop...
GUI/Draw: OpenGL Error: GL_INVALID_OPERATION (1282) (Before line:318)
Segmentation fault
```

```
glxinfo | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 13.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 13.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

**Comment by MeisterYeti** [comment] 2018-10-13 13:33
Duplicate of #2

**Closed as completed by MeisterYeti** 2018-10-13 13:33 UTC
